
package com.wondertek.webservice.client;

import com.wondertek.webservice.demo.HelloImpl;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloImplService", targetNamespace = "http://demo.webservice.wondertek.com/", wsdlLocation = "http://192.168.1.108:8989/hellos?wsdl")
public class HelloImplService
    extends Service
{

    private final static URL HELLOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOIMPLSERVICE_EXCEPTION;
    private final static QName HELLOIMPLSERVICE_QNAME = new QName("http://demo.webservice.wondertek.com/", "HelloImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.108:8989/hellos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOIMPLSERVICE_WSDL_LOCATION = url;
        HELLOIMPLSERVICE_EXCEPTION = e;
    }

    public HelloImplService() {
        super(__getWsdlLocation(), HELLOIMPLSERVICE_QNAME);
    }

    public HelloImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOIMPLSERVICE_QNAME, features);
    }

    public HelloImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOIMPLSERVICE_QNAME);
    }

    public HelloImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOIMPLSERVICE_QNAME, features);
    }

    public HelloImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloImpl
     */
    @WebEndpoint(name = "HelloImplPort")
    public HelloImpl getHelloImplPort() {
        return super.getPort(new QName("http://demo.webservice.wondertek.com/", "HelloImplPort"), HelloImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloImpl
     */
    @WebEndpoint(name = "HelloImplPort")
    public HelloImpl getHelloImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.webservice.wondertek.com/", "HelloImplPort"), HelloImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOIMPLSERVICE_EXCEPTION;
        }
        return HELLOIMPLSERVICE_WSDL_LOCATION;
    }

}
